model_train_type = "sdxl-finetune"
pretrained_model_name_or_path = "./sd-models/animagineXLV3_v30.safetensors"
v2 = false
train_data_dir = "./train"
resolution = "1536,1536"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1536
bucket_reso_steps = 64
output_name = "ghost_test2"
output_dir = "./output"
save_model_as = "safetensors"
save_precision = "fp16"
save_every_n_epochs = 1
max_train_epochs = 10
train_batch_size = 1
gradient_checkpointing = true
learning_rate = 0.000004
learning_rate_te1 = 5e-7
learning_rate_te2 = 5e-7
lr_scheduler = "constant_with_warmup"
lr_warmup_steps = 0
optimizer_type = "AdaFactor"
min_snr_gamma = 5
sample_prompts = "(masterpiece, best quality:1.2), 1girl, solo, --n lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry,  --w 1024  --h 1024  --l 7  --s 20  --d 1337"
sample_sampler = "dpm_2"
sample_every_n_epochs = 1
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
shuffle_caption = true
weighted_captions = false
keep_tokens = 0
max_token_length = 255
noise_offset = 0.1
seed = 1337
no_token_padding = false
mixed_precision = "fp16"
full_fp16 = true
xformers = true
lowram = false
cache_latents = true
cache_latents_to_disk = true
persistent_data_loader_workers = true
optimizer_args = [
  "scale_parameter=False",
  "relative_step=False",
  "warmup_init=False"
]
train_text_encoder = true
